# Generated by Django 4.0.4 on 2022-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=120, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Заказчик'), ('Supplier', 'Поставщик')], max_length=120, verbose_name='Роль'),
        ),
    ]
