# Generated by Django 4.0.4 on 2022-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='comp_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=120, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ogrn',
            field=models.CharField(max_length=15, unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Заказчик'), ('Supplier', 'Поставщик')], max_length=120, verbose_name='Роль'),
        ),
    ]
