# Generated by Django 4.0.4 on 2022-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_email_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comp_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ogrn',
            field=models.CharField(max_length=15, unique=True, verbose_name='ОГРН'),
        ),
    ]
