# Generated by Django 4.0.4 on 2022-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryorder',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='categoryorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoryorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='categoryorder',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название категории'),
        ),
    ]
