# Generated by Django 4.0.4 on 2022-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryorder',
            name='image',
            field=models.ImageField(blank=True, default='category_order/default/placeholder_300x150.png', upload_to='category_order/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Активно'), ('Not Active', 'Не активно'), ('Done', 'Выполнен')], default='Active', max_length=120, verbose_name='Статус'),
        ),
    ]
