# Generated by Django 4.0.4 on 2022-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_responseorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responseorder',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterField(
            model_name='responseorder',
            name='status',
            field=models.CharField(choices=[('On Approval', 'На согласовании'), ('Approved', 'Утвержден'), ('Not Approved', 'Не утвержден'), ('Cancelled', 'Отменен')], max_length=120, verbose_name='Статус'),
        ),
    ]
