# Generated by Django 4.0.4 on 2022-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_responseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Активно'), ('Not Active', 'Не активно')], max_length=120, verbose_name='Статус'),
        ),
    ]
