# Generated by Django 4.0.4 on 2022-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryorder',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
