# Generated by Django 4.0.4 on 2022-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_categoryorder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryorder',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_order/%Y/%m/%d/'),
        ),
    ]
